---
development:
  cloud_name: ENV['CLOUD_NAME']
  api_key: ENV['CLOUDINARY_API_KEY']
  api_secret: ENV['CLOUDINARY_SECRET_API_KEY']
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ENV['CLOUD_NAME']
  api_key: ENV['CLOUDINARY_API_KEY']
  api_secret: ENV['CLOUDINARY_SECRET_API_KEY']
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ENV['CLOUD_NAME']
  api_key: ENV['CLOUDINARY_API_KEY']
  api_secret: ENV['CLOUDINARY_SECRET_API_KEY']
  enhance_image_tag: true
  static_image_support: false
